CREATE DATABASE BANKING_SYSTEM GO USE BANKING_SYSTEM GO CREATE TABLE BANK( BANK_ID VARCHAR(5), BANK_NAME VARCHAR(15), BANK_ADDRESS VARCHAR(50), BANK_EMAIL VARCHAR(25), PRIMARY KEY (BANK_ID) );

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID VARCHAR(10),
    EMPLOYEE_NAME VARCHAR(25),
    EMPLOYEE_SURNAME VARCHAR(25),
    PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE EMPLOYEE(
    E_ID VARCHAR(10),
    PRIMARY KEY(E_ID)
);

CREATE TABLE MANAGER(
    MANAGER_ID VARCHAR(10),
    PRIMARY KEY(MANAGER_ID)
);

CREATE TABLE BRANCH(
    BRANCH_ID VARCHAR(5),
    BRANCH_NAME VARCHAR(20),
    BRANCH_ADDRESS VARCHAR(50),
    EMPLOYEE_ID VARCHAR(10),
    PRIMARY KEY (BRANCH_ID, BRANCH_NAME),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID VARCHAR(10),
    CUSTOMER_NAME VARCHAR(10),
    CUSTOMER_SURNAME VARCHAR(10),
    CUSTOMER_CITY VARCHAR(10),
    CUSTOMER_ADDRESS VARCHAR(50),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE LOAN(
    LOAN_ID VARCHAR(10),
    AMOUNT NUMERIC(15, 2),
    BRANCH_NAME VARCHAR(20),
    BRANCH_ID VARCHAR(5),
    PRIMARY KEY(LOAN_ID),
    FOREIGN KEY (BRANCH_ID, BRANCH_NAME) REFERENCES BRANCH
);

CREATE TABLE CREDIT_CARD(
    CREDIT_CARD_ID VARCHAR(16),
    EXPIRE_DATE DATE,
    LIMIT NUMERIC(10, 2),
    CCV NUMERIC(3),
    PRIMARY KEY (CREDIT_CARD_ID)
);

CREATE TABLE ACCOUNT(
    ACCOUNT_ID VARCHAR(16),
    BALANCE NUMERIC(15),
    CATEGORY VARCHAR(15),
    CCV NUMERIC(3),
    EXPIRE_DATE DATE,
    PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE BORROWER(
    CUSTOMER_ID VARCHAR(10),
    LOAN_ID VARCHAR(10),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER,
    FOREIGN KEY (LOAN_ID) REFERENCES LOAN
);

CREATE TABLE CUSTOMER_CREDIT_CARD(
    CUSTOMER_ID VARCHAR(10),
    CREDIT_CARD_ID VARCHAR(16),
    ACCOUNT_ID VARCHAR(16),
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER,
    FOREIGN KEY (CREDIT_CARD_ID) REFERENCES CREDIT_CARD,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT
);

CREATE TABLE BANKER(
    BRANCH_ID VARCHAR(5),
    CUSTOMER_ID VARCHAR(10),
    BANK_ID VARCHAR(5),
    FOREIGN KEY (BRANCH_ID) REFERENCES BANK,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER,
    FOREIGN KEY (BANK_ID)REFERENCES BANK
);

--Adding is a hierarchy
ALTER TABLE MANAGER ADD CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES
 --Adding is a hierarchy
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE FOREIGN KEY (E_ID) REFERENCES EMPLOYEES